---

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# caddy_ansible.caddy_ansible
caddy_config: |
  {{ cctv_domain }} {
    reverse_proxy localhost:5000

    header {
      Strict-Transport-Security max-age=15552000
    }

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"