---

package_list:
  - name: sudo
  - name: php
  - name: php-fpm
  - name: php-cli
  - name: php-mysql
  - name: php-pgsql
  - name: php-mbstring

# caddy_ansible.caddy_ansible
caddy_config: |
  {{ db_domain }} {
    root * /var/www/adminer
    php_fastcgi unix//run/php/php7.4-fpm.sock
    file_server

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"

# geerlingguy.adminer
adminer_install_dir: /var/www/adminer
adminer_install_filename: index.php