---

# geerlingguy.pip
pip_install_packages:
  - name: mkdocs
  - name: mkdocs-material
  - name: mkdocs-awesome-pages-plugin

# caddy_ansible.caddy_ansible
caddy_config: |
  {{ docs_domain }} {
    root * /var/www/lab-docs/site
    file_server

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"