---

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_install_compose: true
docker_compose_version: "2.18.1"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

# caddy_ansible.caddy_ansible
caddy_config: |
  {{ media_domain }} {
    reverse_proxy localhost:32400

    route /tautulli* {
      reverse_proxy localhost:8181
    }
    redir /tautulli /tautulli/
    
    route /overseerr* {
      reverse_proxy localhost:5055
    }
    redir /overseerr /overseerr/

    route /sonarr* {
      reverse_proxy localhost:8989
    }
    redir /sonarr /sonarr/

    route /radarr* {
      reverse_proxy localhost:7878
    }
    redir /radarr /radarr/

    route /sabnzbd* {
      reverse_proxy localhost:8080
    }
    redir /sabnzbd /sabnzbd/

    route /lidarr* {
      reverse_proxy localhost:8686
    }
    redir /lidarr /lidarr/

    header {
      Strict-Transport-Security max-age=15552000
    }

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"