---

# geerlingguy.pip
pip_install_packages:
  - name: docker

docker_install_compose: true
docker_compose_version: "1.26.0"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

caddy_config: |
  http://localhost:2020
  respond "Hello, world!"
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true