---

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_install_compose: true
docker_compose_version: "1.26.0"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

# docker-compose file
docker_compose:
  version: '2'
  services:
    db:
      image: mariadb:10.6
      restart: always
      command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
      volumes:
        - "{{ nextcloud_storage_location }}/database:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD={{ nextcloud_db_pass }}"
        - "MYSQL_PASSWORD={{ nextcloud_db_pass }}"
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud

    app:
      image: nextcloud
      restart: always
      links:
        - db
      volumes:
        - "{{ nextcloud_storage_location }}/html:/var/www/html"
        - "{{ nextcloud_storage_location }}/storage:/data"
      environment:
        - TRUSTED_PROXIES=10.51.1.1
        - OVERWRITEPROTOCOL=https
        - "NEXTCLOUD_TRUSTED_DOMAINS= {{ nextcloud_domain }}"
        - APACHE_DISABLE_REWRITE_IP=1
        - "MYSQL_PASSWORD={{ nextcloud_db_pass }}"
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_HOST=db
        - REDIS_HOST=redis
        - NEXTCLOUD_DATA_DIR=/data
        - "SMTP_HOST={{ smtp_server }}"
        - SMTP_SECURE=ssl
        - "SMTP_PORT={{ smtp_port }}"
        - "SMTP_NAME={{ smtp_user }}"
        - "SMTP_PASSWORD={{ smtp_pass }}"
        - "MAIL_FROM_ADDRESS={{ smtp_from }}"
      ports:
        - 8080:80
      depends_on:
        - db
        - redis
        - cron
    
    redis:
      image: redis:alpine
      container_name: redis
      restart: always
    
    cron:
      container_name: cron
      image: nextcloud
      restart: always
      volumes:
        - "{{ nextcloud_storage_location }}/html:/var/www/html"
        - "{{ nextcloud_storage_location }}/storage:/data"
      environment:
        - NEXTCLOUD_DATA_DIR=/data
      entrypoint: /cron.sh