---

# geerlingguy.pip
pip_install_packages:
  - name: docker


caddy_config: |
  http://localhost:2020
  respond "Hello, world!"
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true