---

# geerlingguy.pip
pip_install_packages:
  - name: docker

# geerlingguy.docker
docker_install_compose: true
docker_compose_version: "1.26.0"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

# caddy_ansible.caddy_ansible
caddy_config: |
  nc-test.int.moras.uk {
    reverse_proxy localhost:8080

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"