---

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_install_compose: true
docker_compose_version: "1.26.0"
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose

# caddy_ansible.caddy_ansible
caddy_config: |
  {{ paperless_domain }} {
    reverse_proxy localhost:8050

    header {
      Strict-Transport-Security max-age=15552000
    }

    tls logs@moras.dev {
      dns cloudflare {{ cloudflare_dns_token }}
    }
  }
caddy_update: true
caddy_packages: [
  "github.com/caddy-dns/cloudflare"
]
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"

# docker-compose file
docker_compose:
  version: "3.4"
  services:
    broker:
      image: redis:7
      restart: unless-stopped
      volumes:
        - redis:/data

    db:
      image: mariadb:10
      restart: unless-stopped
      volumes:
        - "{{ paperless_storage_location }}/database:/var/lib/mysql"
      environment:
        - MARIADB_HOST=paperless
        - MARIADB_DATABASE=paperless
        - MARIADB_USER=paperless
        - "MARIADB_PASSWORD={{ paperless_database_password }}"
        - "MARIADB_ROOT_PASSWORD={{ paperless_database_password }}"

    webserver:
      image: ghcr.io/paperless-ngx/paperless-ngx:latest
      restart: unless-stopped
      depends_on:
        - db
        - broker
      ports:
        - "8050:8000"
      volumes:
        - "{{ paperless_storage_location }}/data:/usr/src/paperless/data"
        - "{{ paperless_storage_location }}/media:/usr/src/paperless/media"
        - "{{ paperless_storage_location }}/export:/usr/src/paperless/export"
        - "{{ paperless_storage_location }}/consume:/usr/src/paperless/consume"
      environment:
        - PAPERLESS_REDIS=redis://broker:6379
        - PAPERLESS_DBENGINE=mariadb
        - PAPERLESS_DBHOST=db
        - PAPERLESS_DBUSER=paperless
        - "PAPERLESS_DBPASS={{ paperless_database_password }}"
        - PAPERLESS_DBPORT=3306
        - PAPERLESS_OCR_LANGUAGE=eng+cym
        - PAPERLESS_OCR_LANGUAGES=eng cym
        - PAPERLESS_TIME_ZONE=Europe/London
        - "PAPERLESS_URL=https://{{ paperless_domain }}"
        - "PAPERLESS_SECRET_KEY={{ paperless_secret_key }}"

  volumes:
    redis: