---

- name: Add CrowdSec repository
  block:
    - name: Install apt repo management packages
      ansible.builtin.apt:
        pkg:
        - debian-archive-keyring
        - apt-transport-https
        - gnupg
        - curl
        update_cache: yes

    - name: Create directory for keys
      ansible.builtin.command:
        cmd: mkdir -p /etc/apt/keyrings/

    - name: Get signing key
      ansible.builtin.get_url:
        url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
        dest: /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.asc

    - name: Add repo to sources
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.asc] https://packagecloud.io/crowdsec/crowdsec/debian {{ ansible_distribution_release }} main"
        state: present
    
    - name: Add repo to sources
      ansible.builtin.apt_repository:
        repo: "deb-src [signed-by=/etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.asc] https://packagecloud.io/crowdsec/crowdsec/debian {{ ansible_distribution_release }} main"
        state: present

- name: Install CrowdSec
  ansible.builtin.apt:
    pkg:
    - crowdsec
    - crowdsec-firewall-bouncer-iptables
    update_cache: yes

- name: Install Caddy Collection
  ansible.builtin.command:
    cmd: cscli parsers install crowdsecurity/caddy-logs