---

- name: ensure target dir exists
  file:
    dest: "{{ frigate_storage_location }}/"
    state: directory

- name: template frigate config
  template:
    src: templates/config.yml.j2
    dest: "{{ frigate_storage_location }}/config.yml"

- name: Deploy frigate docker container
  community.docker.docker_compose:
    project_name: frigate
    definition: "{{ frigate_docker_compose }}"
    pull: true
    recreate: always