roles:
  - src: geerlingguy.docker
  - src: geerlingguy.pip
  - src: grog.package
  - src: geerlingguy.security
  - src: geerlingguy.ntp
  - src: weareinteractive.environment
  - src: caddy_ansible.caddy_ansible
  - src: oefenweb.dnsmasq

collections:
  - name: community.docker