---
# DEFAULT VARIABLES #
paperless_database_host: db
paperless_database_password: password
paperless_storage_location: ~/paperless
paperless_domain: paperless
paperless_secret_key: secretkey

# DOCKER COMPOSE #
paperless_docker_compose:
  version: "3.4"
  services:
    broker:
      image: redis:7
      restart: unless-stopped
      volumes:
        - redis:/data

    webserver:
      image: ghcr.io/paperless-ngx/paperless-ngx:latest
      restart: unless-stopped
      depends_on:
        - broker
      ports:
        - "8000:8000"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
        - "{{ paperless_storage_location }}/data:/usr/src/paperless/data"
        - "{{ paperless_storage_location }}/media:/usr/src/paperless/media"
        - "{{ paperless_storage_location }}/export:/usr/src/paperless/export"
        - "{{ paperless_storage_location }}/consume:/usr/src/paperless/consume"
      environment:
        - PAPERLESS_REDIS=redis://broker:6379
        - PAPERLESS_DBENGINE=postgresql
        - "PAPERLESS_DBHOST={{ paperless_database_host }}"
        - PAPERLESS_DBUSER=paperless
        - PAPERLESS_DBNAME=paperless
        - "PAPERLESS_DBPASS={{ paperless_database_password }}"
        - PAPERLESS_DBPORT=5432
        - PAPERLESS_OCR_LANGUAGE=eng+cym
        - PAPERLESS_OCR_LANGUAGES=eng cym
        - PAPERLESS_TIME_ZONE=Europe/London
        - "PAPERLESS_URL=https://{{ paperless_domain }}"
        - "PAPERLESS_SECRET_KEY={{ paperless_secret_key }}"
        - PAPERLESS_TIKA_ENABLED=1
        - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
        - PAPERLESS_TIKA_ENDPOINT=http://tika:9998

    gotenberg:
      image: docker.io/gotenberg/gotenberg:7.8
      restart: unless-stopped

      # The gotenberg chromium route is used to convert .eml files. We do not
      # want to allow external content like tracking pixels or even javascript.
      command:
        - "gotenberg"
        - "--chromium-disable-javascript=true"
        - "--chromium-allow-list=file:///tmp/.*"

    tika:
      image: ghcr.io/paperless-ngx/tika:latest
      restart: unless-stopped

  volumes:
    redis: