---

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: ~/.config/pip
    state: directory

- name: Add Pip config options to break packages
  ansible.builtin.copy:
    src: files/pip.conf
    dest: ~/.config/pip