---
# DEFAULT VARIABLES #
# These can be overriden in the group_vars files or in the vault
servarr_storage_location: ~/servarr
servarr_puid: 0
servarr_pgid: 0

# DOCKER COMPOSE #
servarr_docker_compose:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - '{{ servarr_storage_location }}/lidarr:/config'
      - '{{ servarr_storage_location }}/music:/music'
      - '{{ servarr_storage_location }}/nzb/complete:/downloads'
    environment:
      - 'PUID={{ servarr_puid }}'
      - 'PGID={{ servarr_pgid }}'
    ports:
      - 8686:8686
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - '{{ servarr_storage_location }}/radarr:/config'
      - '{{ servarr_storage_location }}/films:/movies'
      - '{{ servarr_storage_location }}/nzb/complete:/downloads'
    environment:
      - 'PUID={{ servarr_puid }}'
      - 'PGID={{ servarr_pgid }}'
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - '{{ servarr_storage_location }}/sonarr:/config'
      - '{{ servarr_storage_location }}/tv:/tv'
      - '{{ servarr_storage_location }}/nzb/complete:/downloads'
    environment:
      - 'PUID={{ servarr_puid }}'
      - 'PGID={{ servarr_pgid }}'
    ports:
      - 8989:8989
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    volumes:
      - '{{ servarr_storage_location }}/sabnzbd:/config'
      - '{{ servarr_storage_location }}/nzb/complete:/downloads'
      - '{{ servarr_storage_location }}/nzb/incomplete:/incomplete-downloads'
    environment:
      - 'PUID={{ servarr_puid }}'
      - 'PGID={{ servarr_pgid }}'
    ports:
      - 8080:8080
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - '{{ servarr_storage_location }}/overseerr:/config'
    environment:
      - 'PUID={{ servarr_puid }}'
      - 'PGID={{ servarr_pgid }}'
    ports:
      - 5055:5055
    restart: unless-stopped