---

# DEFAULT VARIABLES #
frigate_storage_location: /root/frigate

# Docker Compose
frigate_docker_compose:
  version: "3.9"
  services:
    frigate:
      container_name: frigate
      restart: unless-stopped
      image: ghcr.io/blakeblackshear/frigate:stable
      shm_size: "128mb" # update for your cameras based on calculation above
      devices:
        - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - '{{ frigate_storage_location }}/config.yml:/config/config.yml:ro'
        - '{{ frigate_storage_location }}:/media/frigate'
        - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 1000000000
      ports:
        - "5000:5000"
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp
      environment:
        - LIBVA_DRIVER_NAME=i965
        - 'PLUS_API_KEY={{ frigate_plus_api_key }}'