---

- name: Pull git repo
  git:
    repo: 'git@github.com:alexmoras/lab-wiki.git'
    dest: /var/www/lab-docs

- name: Build mkdocs site
  script:
    chdir: /var/www/lab-docs
    cmd: /usr/local/bin/mkdocs build